# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 196ed3b3793dfa826f223a35ad2fbea2749ca71cc64607e29ab0d1782b1c736a73d7fabce33e1815ca7099858db94557f6a0456372421a87b5c8d9ec9cba1416

test:
  secret_key_base: e9e1f47193ff63f7fe63d6db129ba619354a56fc37af09ffbf1b483f6bdbe0de3e3c0c2283587f0c5a3f930afb3692b6214beacb92912cd9441dd1f28eaf3371

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
